### PR TITLE
Post Conference stage

### PR DESCRIPTION
**Pull request by romanschejbal**
# Based on [these](https://app.zeplin.io/project.html#pid=57bac5a5323e4f1d1167b761&dashboard&tags=PostConference)

## How to test
To fake (for testing purposes only as it'll be removed later) the 1st stage of post conference state, put this at the end of the url `/post-conference`. For the 2nd stage it is `/post-conference-final`

### Todo 
Stage 1
- [x] Update ConferenceAbout box
- [x] Instagram photos
- [x] Tweets
- [x] Headings include icons
- [x] Change hashtag to #ReactLondon2017

Stage 2
- [x] Linkedin Slides from Slideshare
- [x] Youtube playlists
- [x] Photos on Flickr (6 photos instead of 3)

# Before Merge - Stage 1
- [ ] Change home route to point the new post conference state (see `shared/routes/conference-routes/index.js`)
- [ ] Update instagram section with real data
- [ ] Update twitter section with real data

# Before Merge - Stage 2
- [ ] Update route to pass down `finalStage` prop (in `shared/routes/conference-routes/index.js`)
- [ ] Update flickr section with real data
- [ ] Update youtube playlists with real data
- [ ] Update slideshare presentations with real data

### CODE REVIEW

**Comment by chris-brookes** [comment]
@romanschejbal - There is a 'finished' misspelling in a header and the dash lines are missing between each set of photos/messages. (on both postconference and postconferencefinal pages) See image attached.

screen shot 2017-03-17 at 14 33 31


Wrong twitter tag. Should be "#ReactLondon2017"

screen shot 2017-03-17 at 15 03 31

**Comment by romanschejbal** [comment]
Thanks for reviewing guys.. Couple things

- [ ] _The styling looks odd on a medium screen size, where there’s only one stretched image per section._ - **It should show 3 images on tablet or 1 image on screen smaller than tablet (portrait) does not that work for you?** 
- [x] _The styles on the buttons should match the styles on the current ‘See more’ button on the home page. Same border radius etc._
- [x] _The html for the speaker youtube and slides should look more like the html on the current home page. With the images inside figure tags and all the text inside h5 tags._
- [ ] _Instead of using background images for the youtubes, img tags would be more accessible._ - **I can't use img tag since the images might have different proportions. So I'm using **`background-size: cover`**. Unless there is a better of solving this?**
- [x] _Should there be rel="noopener" on links that open in new windows like in other areas to the site?_

Screen to design inconsistencies

- [ ] _Mismatch between the play arrow image on the youtubes_ - **still need to implement (missing icon)**
- [x] _Missing dashed lines between sections_
- [x] _Larger gap above See all photos button_
- [ ] _Flickr section instead of Facebook section_ - **we won't be using Facebook**
- [x] _Wrong hashtag in Twitter section_

**Comment by chris-brookes** [comment]
There is a space layout issue with the win10 IE11 browser. A similar issue appears on other pages of the site, but after looking at the browser usage stats we decided to leave the issue, so I will do on this page too.

Still waiting for the new youtube play arrow image.

**Comment by chris-brookes** [comment]
@asavin - We need to change the twitter #title again. Change from #ReactLondon2017 to #ReactLondon 
Places to change:
- In the h3 twitter header
- Text in the button
- The link in the button
(on both post conference pages)

**Pull request merged**
