### PR TITLE
Run app as non-root

### PR DESCRIPTION
**Pull request by lpil**
In docker the user namespace is shared between the host and docker
containers, so root in a container is root on the host.

In the event of the app being compromised running the attacker will only
have access to that user, rather than to the root of the host and all
the containers on the machine. Much better. :)

I should have done this first time round. Oops.

### CODE REVIEW

**Comment by asavin** [comment]
Nice one!

**Comment by lpil** [comment]
FYI the image is still building on my machine, so it's untested. npm is slooooooooooooow

**Comment by lpil** [comment]
Seems to work but I don't have all the env so couldn't test 100%

**Comment by asavin** [comment]
Ok I think Circle is not going to pick up this PR :-O

**Comment by asavin** [comment]
I'm going to merge this into a local branch and then we can follow the normal flow from there.

**Pull request merged**
