### PR TITLE
Add meta information for social networks

### PR DESCRIPTION
**Pull request by Etiene**
* This should add meta information for sharing links of react london on twitter or facebook
* You should test it here, for example: https://developers.facebook.com/tools/debug/og/object/

### CODE REVIEW

**Comment by gregdorward** [comment]
@asavin / @Etiene is this how you would expect the sharing link to look? I haven't seen any designs for this, so I'm hoping you have?

screen shot 2017-02-16 at 10 01 26

**Comment by asavin** [comment]
@gregdorward yeah that doesn't look great

**Comment by gregdorward** [comment]
Shall we get UX input on this one then?

**Comment by asavin** [comment]
@gregdorward yes

**Comment by gregdorward** [comment]
@stevecottle - do you have an opinion on the screenshot shown above? This is what a user would see if they shared the React London site on Facebook or Twitter. Do you think it needs resizing, or a different image altogether?

**Comment by Etiene** [comment]
@gregdorward there is a bug to be solved concerning the server rendering that @asavin pointed yesterday! I'll flag with a `ready for test` once this is solved

**Comment by Etiene** [comment]
Unfortunately I think it won't be possible to do a branch test on this feature because facebook will still scrape the canonical url from `react.london` and not from our staging url. We will have to deploy this first and double check.
cc @stevecottle @gregdorward

**Comment by gregdorward** [comment]
Ok @Etiene, if that's the case we'll just have to check it in production. Will the link you provided still be the way to test in once it's there?

**Comment by Etiene** [comment]
@gregdorward yes, it will be the same facebook url

**Comment by gregdorward** [comment]
Is this what you were expecting after this change @Etiene ?

screen shot 2017-02-17 at 10 52 18

**Pull request merged**
