### PR TITLE
Deactivated 'Call for papers' and 'Become a speaker' links

### PR DESCRIPTION
**Pull request by grahammendick**
On the 31st January the Call For Papers and Become a Speaker become obsolete.
(In the CFP, the link to 'React meetup' behaves the same as the 'Find our more' link in the footer)
The implementation differs from the Zeplin designs slightly (the changes came about after discussions with sari)
* Call for Papers - Changed the button colours to make it look disabled
* Become a Speaker - Kept image on home page. Left aligned message with text, not image

### CODE REVIEW

**Comment by asavin** [comment]
Looks good.

Are we removing "Could this be you? Become a speaker" links as a separate PR?

**Comment by grahammendick** [comment]
@asavin i was going to, but happy to include it as part of this? what do you think is better?

**Comment by asavin** [comment]
I'd say let's do it in the same PR since it is not huge

**Comment by asavin** [comment]
LGTM

We can merge this today and release to live tomorrow.

**Pull request merged**
